FROM node:22.16-bookworm-slim AS frontend-build

WORKDIR /app/frontend

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    g++ \
    make \
    pkg-config \
    python3 \
    libusb-1.0-0-dev \
  && rm -rf /var/lib/apt/lists/*

COPY frontend/package*.json ./
RUN npm ci

COPY frontend ./

ARG VITE_PRIVY_APP_ID
ARG VITE_STELLAR_NETWORK
ARG VITE_STELLAR_RPC_URL
ARG VITE_STELLAR_HORIZON_URL
ARG VITE_STELLAR_EXPLORER_URL
ARG VITE_DEAL_ESCROW_CONTRACT
ARG VITE_USDC_TOKEN_ADDRESS
ARG VITE_SETTLEMENT_TOKEN_SYMBOL
ARG VITE_SETTLEMENT_TOKEN_NAME
ARG VITE_SETTLEMENT_TOKEN_DECIMALS
ARG VITE_SETTLEMENT_MIN_UNITS
ARG VITE_SETTLEMENT_ASSET_POLICY
ARG VITE_STELLAR_BROKER_PROVIDER
ARG VITE_STELLAR_BROKER_SLIPPAGE_BPS
ARG VITE_STELLAR_BROKER_QUOTE_TTL_SECONDS
ARG VITE_SOROSWAP_ROUTER_ADDRESS
ARG VITE_SOROSWAP_POOL_ADDRESS
ARG VITE_PRIVY_FIAT_ONRAMP_ENABLED
ARG VITE_PRIVY_FIAT_ONRAMP_ENVIRONMENT
ARG VITE_PRIVY_FIAT_ONRAMP_DESTINATION_CHAIN
ARG VITE_PRIVY_FIAT_ONRAMP_DESTINATION_ASSET
ARG VITE_PRIVY_FIAT_ONRAMP_DEFAULT_AMOUNT
ARG VITE_PRIVY_FIAT_ONRAMP_SOURCE_ASSETS
ARG VITE_PRIVY_FIAT_ONRAMP_DEFAULT_SOURCE_ASSET

ENV VITE_PRIVY_APP_ID=$VITE_PRIVY_APP_ID
ENV VITE_STELLAR_NETWORK=$VITE_STELLAR_NETWORK
ENV VITE_STELLAR_RPC_URL=$VITE_STELLAR_RPC_URL
ENV VITE_STELLAR_HORIZON_URL=$VITE_STELLAR_HORIZON_URL
ENV VITE_STELLAR_EXPLORER_URL=$VITE_STELLAR_EXPLORER_URL
ENV VITE_DEAL_ESCROW_CONTRACT=$VITE_DEAL_ESCROW_CONTRACT
ENV VITE_USDC_TOKEN_ADDRESS=$VITE_USDC_TOKEN_ADDRESS
ENV VITE_SETTLEMENT_TOKEN_SYMBOL=$VITE_SETTLEMENT_TOKEN_SYMBOL
ENV VITE_SETTLEMENT_TOKEN_NAME=$VITE_SETTLEMENT_TOKEN_NAME
ENV VITE_SETTLEMENT_TOKEN_DECIMALS=$VITE_SETTLEMENT_TOKEN_DECIMALS
ENV VITE_SETTLEMENT_MIN_UNITS=$VITE_SETTLEMENT_MIN_UNITS
ENV VITE_SETTLEMENT_ASSET_POLICY=$VITE_SETTLEMENT_ASSET_POLICY
ENV VITE_STELLAR_BROKER_PROVIDER=$VITE_STELLAR_BROKER_PROVIDER
ENV VITE_STELLAR_BROKER_SLIPPAGE_BPS=$VITE_STELLAR_BROKER_SLIPPAGE_BPS
ENV VITE_STELLAR_BROKER_QUOTE_TTL_SECONDS=$VITE_STELLAR_BROKER_QUOTE_TTL_SECONDS
ENV VITE_SOROSWAP_ROUTER_ADDRESS=$VITE_SOROSWAP_ROUTER_ADDRESS
ENV VITE_SOROSWAP_POOL_ADDRESS=$VITE_SOROSWAP_POOL_ADDRESS
ENV VITE_PRIVY_FIAT_ONRAMP_ENABLED=$VITE_PRIVY_FIAT_ONRAMP_ENABLED
ENV VITE_PRIVY_FIAT_ONRAMP_ENVIRONMENT=$VITE_PRIVY_FIAT_ONRAMP_ENVIRONMENT
ENV VITE_PRIVY_FIAT_ONRAMP_DESTINATION_CHAIN=$VITE_PRIVY_FIAT_ONRAMP_DESTINATION_CHAIN
ENV VITE_PRIVY_FIAT_ONRAMP_DESTINATION_ASSET=$VITE_PRIVY_FIAT_ONRAMP_DESTINATION_ASSET
ENV VITE_PRIVY_FIAT_ONRAMP_DEFAULT_AMOUNT=$VITE_PRIVY_FIAT_ONRAMP_DEFAULT_AMOUNT
ENV VITE_PRIVY_FIAT_ONRAMP_SOURCE_ASSETS=$VITE_PRIVY_FIAT_ONRAMP_SOURCE_ASSETS
ENV VITE_PRIVY_FIAT_ONRAMP_DEFAULT_SOURCE_ASSET=$VITE_PRIVY_FIAT_ONRAMP_DEFAULT_SOURCE_ASSET

RUN npm run build

FROM node:22.16-bookworm-slim AS indexer-build

WORKDIR /app/indexer

COPY indexer/package*.json ./
RUN npm ci

COPY indexer ./
RUN npm run build
RUN npm prune --omit=dev

FROM node:22.16-bookworm-slim

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV FRONTEND_DIST_PATH=/app/frontend-dist

COPY --from=indexer-build /app/indexer/package*.json ./indexer/
COPY --from=indexer-build /app/indexer/node_modules ./indexer/node_modules
COPY --from=indexer-build /app/indexer/dist ./indexer/dist
COPY --from=frontend-build /app/frontend/dist ./frontend-dist

EXPOSE 3000

CMD ["node", "indexer/dist/server.js"]
